export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  SCHOOL_OWNER: 'SCHOOL_OWNER',
  PRINCIPAL: 'PRINCIPAL',
  VICE_PRINCIPAL: 'VICE_PRINCIPAL',
  TEACHER: 'TEACHER',
  CLASS_TEACHER: 'CLASS_TEACHER',
  STUDENT: 'STUDENT',
  PARENT: 'PARENT',
  ACCOUNTANT: 'ACCOUNTANT',
  LIBRARIAN: 'LIBRARIAN',
  HOSTEL_MANAGER: 'HOSTEL_MANAGER',
  NURSE: 'NURSE',
  RECEPTIONIST: 'RECEPTIONIST',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_HIERARCHY: Record<Role, number> = {
  SUPER_ADMIN: 100,
  SCHOOL_OWNER: 90,
  PRINCIPAL: 80,
  VICE_PRINCIPAL: 70,
  ACCOUNTANT: 60,
  LIBRARIAN: 60,
  HOSTEL_MANAGER: 60,
  NURSE: 60,
  RECEPTIONIST: 50,
  CLASS_TEACHER: 45,
  TEACHER: 40,
  PARENT: 30,
  STUDENT: 20,
};

export const ROLE_PERMISSIONS: Record<Role, string[]> = {
  SUPER_ADMIN: ['*'],
  SCHOOL_OWNER: [
    'dashboard:view',
    'students:manage',
    'staff:manage',
    'academic:manage',
    'finance:manage',
    'settings:manage',
    'reports:view',
  ],
  PRINCIPAL: [
    'dashboard:view',
    'students:view',
    'students:manage',
    'staff:view',
    'staff:manage',
    'academic:manage',
    'attendance:view',
    'reports:view',
  ],
  VICE_PRINCIPAL: [
    'dashboard:view',
    'students:view',
    'students:manage',
    'staff:view',
    'academic:manage',
    'attendance:view',
    'reports:view',
  ],
  ACCOUNTANT: [
    'dashboard:view',
    'finance:manage',
    'finance:view',
    'reports:view',
  ],
  LIBRARIAN: ['library:manage', 'library:view'],
  HOSTEL_MANAGER: ['hostel:manage', 'hostel:view'],
  NURSE: ['clinic:manage', 'clinic:view'],
  RECEPTIONIST: ['students:view', 'visitors:manage'],
  CLASS_TEACHER: [
    'dashboard:view',
    'students:view',
    'academic:manage',
    'attendance:manage',
    'grades:manage',
    'homework:manage',
  ],
  TEACHER: [
    'dashboard:view',
    'students:view',
    'academic:manage',
    'attendance:manage',
    'grades:manage',
    'homework:manage',
  ],
  PARENT: [
    'dashboard:view',
    'children:view',
    'results:view',
    'attendance:view',
    'fees:view',
    'homework:view',
    'messages:send',
  ],
  STUDENT: [
    'dashboard:view',
    'results:view',
    'attendance:view',
    'homework:view',
    'timetable:view',
    'cbt:attempt',
    'downloads:view',
  ],
};
